sudo: false
language: node_js
node_js:
  - "6.3.1"
before_install:
  - if [ "$TRAVIS_NODE_VERSION" = "0.10" ]; then npm install -g npm@2; fi
  - gem update --system
  - gem install sass
matrix:
  fast_finish: true
cache:
  directories:
    - node_modules
before_script:
  - npm install -g typings bower grunt-cli
  - npm install
script:
  - grunt build
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/232187bff2b9f15cfc50
    on_success: always
    on_failure: always
    on_start: never